services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: worksphere
      POSTGRES_PASSWORD: worksphere
      POSTGRES_DB: worksphere
    volumes:
      - worksphere_pg:/var/lib/postgresql/data

volumes:
  worksphere_pg:
